name: Upload to Google Drive

on:
  push:
    paths:
      - 'file.csv' # Adjust the file name you want to upload

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Upload to Google Drive
      env:
        API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
      run: |
        # Install gdrive (if not already installed)
        wget -O gdrive https://github.com/glotlabs/gdrive/releases/tag/3.9.0/gdrive-linux-x64
        chmod +x gdrive
        sudo install gdrive /usr/local/bin/gdrive

        # Upload the file to Google Drive using gdrive
        FILE_TO_UPLOAD="file.csv" # Adjust the file name
        ./upload-to-drive.sh "${FILE_TO_UPLOAD}" "${API_KEY}"
