name: Download from Google Drive

on:
  workflow_dispatch:
    inputs:
      file_id:
        description: 'Google Drive file ID to download'
        required: true
      output_path:
        description: 'Output directory (optional, defaults to repository root)'
        required: false
        default: '.'
      output_name:
        description: 'Name for downloaded file (optional, uses original name if not provided)'
        required: false

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download file from Google Drive
      run: |
        FILE_ID="${{ github.event.inputs.file_id }}"
        OUTPUT_PATH="${{ github.event.inputs.output_path || '.' }}"
        OUTPUT_NAME="${{ github.event.inputs.output_name }}"
        
        echo "Downloading file ID: $FILE_ID"
        echo "Output directory: $OUTPUT_PATH"
        
        # Create output directory if it doesn't exist
        mkdir -p "$OUTPUT_PATH"
        
        if [ -n "$OUTPUT_NAME" ]; then
          python3 google_drive_helper.py download \
            --file-id "$FILE_ID" \
            --output-path "$OUTPUT_PATH" \
            --output-name "$OUTPUT_NAME"
        else
          python3 google_drive_helper.py download \
            --file-id "$FILE_ID" \
            --output-path "$OUTPUT_PATH"
        fi
      env:
        GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}

    - name: Upload downloaded files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: downloaded-files
        path: ${{ github.event.inputs.output_path || '.' }}/*
        retention-days: 30
